import React, { useState } from 'react';
import { Modal, Box, Button, Select, MenuItem, InputLabel, FormControl } from '@mui/material';
import axios from 'axios';

const style = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    boxShadow: 24,
    p: 4,
    borderRadius: '8px',
};

const AircraftCreateModal = ({ isOpen, onClose, onAircraftCreated }) => {
    const [aircraftType, setAircraftType] = useState('');
    const [errorMessage, setErrorMessage] = useState('');

    const handleCreateAircraft = async (e) => {
        e.preventDefault();
        setErrorMessage('');

        const token = localStorage.getItem('token');
        try {
            await axios.post('/api/aircrafts/', {
                name: aircraftType, // Send only name, since serial_number is generated by backend
            }, {
                headers: { Authorization: `Token ${token}` },
            });
            onAircraftCreated(); // Notify parent to refresh the aircraft list
            onClose(); // Close the modal
        } catch (error) {
            if (error.response && error.response.data) {
                const errorMsg = error.response.data.detail || error.response.data[0] || 'An error occurred. Please try again.';
                setErrorMessage(errorMsg);
            } else {
                setErrorMessage('An error occurred. Please try again.');
            }
        }
    };

    return (
        <Modal
            open={isOpen}
            onClose={onClose}
            aria-labelledby="create-aircraft-modal"
            aria-describedby="create-new-aircraft"
        >
            <Box sx={style}>
                <h2 id="create-aircraft-modal">Create New Aircraft</h2>
                {errorMessage && <p style={{ color: 'red' }}>{errorMessage}</p>}
                <FormControl fullWidth sx={{ mt: 2 }}>
                    <InputLabel id="aircraft-type-label">Aircraft Type</InputLabel>
                    <Select
                        fullWidth
                        value={aircraftType}
                        onChange={(e) => setAircraftType(e.target.value)}
                        variant={'filled'}
                    >
                        <MenuItem value="AKINCI">AKINCI</MenuItem>
                        <MenuItem value="TB2">TB2</MenuItem>
                        <MenuItem value="TB3">TB3</MenuItem>
                        <MenuItem value="KIZILELMA">KIZILELMA</MenuItem>
                    </Select>
                </FormControl>
                <Button
                    variant="contained"
                    color="primary"
                    onClick={handleCreateAircraft}
                    sx={{ mt: 2 }}
                >
                    Create Aircraft
                </Button>
            </Box>
        </Modal>
    );
};

export default AircraftCreateModal;
