# Generated by Django 4.2.5 on 2024-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aircraftpart',
            constraint=models.UniqueConstraint(fields=('part',), name='unique_part_per_aircraft'),
        ),
    ]
