# Generated by Django 4.2.5 on 2024-10-11 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_aircraftpart_unique_part_per_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızılelma')], max_length=20),
        ),
    ]
