# Generated by Django 4.2.5 on 2024-10-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_remove_part_team_team_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='part',
            name='aircraft_type',
            field=models.CharField(choices=[('AKINCI', 'AKINCI'), ('TB2', 'TB2'), ('TB3', 'TB3'), ('KIZILELMA', 'KIZILELMA')], default='AKINCI', max_length=20),
            preserve_default=False,
        ),
    ]
