# Generated by Django 4.2.5 on 2024-10-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0006_remove_aircraftpart_unique_part_per_aircraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='name',
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='aircraftpart',
            constraint=models.UniqueConstraint(fields=('part',), name='unique_part_assignment'),
        ),
    ]
