# Generated by Django 4.2.5 on 2024-10-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_remove_personnel_name_personnel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='parts',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Wing Team', 'Wing Team'), ('Body Team', 'Body Team'), ('Tail Team', 'Tail Team'), ('Avionics Team', 'Avionics Team'), ('Assembly Team', 'Assembly Team')], max_length=50, unique=True),
        ),
    ]
