# Generated by Django 4.2.5 on 2024-10-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_remove_team_parts_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
