# Generated by Django 4.2.5 on 2024-10-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_add_predefined_teams'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aircraftpart',
            name='unique_part_assignment',
        ),
    ]
