# Generated by Django 4.2.5 on 2024-10-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_remove_aircraftpart_unique_part_assignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aircraftpart',
            name='unique_part_per_aircraft',
        ),
    ]
