# Generated by Django 4.2.5 on 2024-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_remove_aircraftpart_unique_part_per_aircraft'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aircraftpart',
            constraint=models.UniqueConstraint(fields=('part',), name='unique_part_assignment'),
        ),
        migrations.AddConstraint(
            model_name='aircraftpart',
            constraint=models.UniqueConstraint(fields=('part', 'aircraft'), name='unique_part_per_aircraft'),
        ),
    ]
